### PR TITLE
Add `cargo-fix` executable

### LINKED ISSUE #32: Rename binary to cargo-fix
After a `cargo install rustfix`, the subcommand `cargo fix` would be available.

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #32

### CODE REVIEW

File: src/bin/cargo-fix.rs [hunk 1]
```diff
@@ -0,0 +1,4 @@
+// horrible hack to get cargo to not complain about both
+// the `cargo-fix` and `rustfix` targets to point to the
+// same source file
+include!{"../main.rs"}
```
Comment (killercup) [inline src/bin/cargo-fix.rs]: why curly braces 😮

Comment (oli-obk) [reply src/bin/cargo-fix.rs]: I have zero opinions.

**Comment by killercup** [comment]
> I have zero opinions.

All hail the round brackets!

bors r+
